// Export standalone Stride artwork, Android icon resources and review sheet.
// This tool does not modify app configuration or installed Android resources.
// Run: npm ci --prefix tools/branding && npm run generate --prefix tools/branding
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const ink = '#1C2520';
const lime = '#D2F36B';
const background = '#F7F8FA';
const muted = '#768079';
const dark = '#202C25';
const ns = 'http://www.w3.org/2000/svg';
const androidNs = 'http://schemas.android.com/apk/res/android';
// One silhouette is shared by the launcher, splash and notification icon.
// Coordinates use the 108 dp adaptive-icon canvas; the mark fits its safe circle.
const paths = [
  'M48 30 H74 Q78 30 78 34 V60 H66 V50.5 L49 67.5 L40.5 59 L57.5 42 H48 Z',
  'M28.5 71 L35.5 64 L44 72.5 L37 79.5 Q35.5 81 34 79.5 L28.5 74 Q27 72.5 28.5 71 Z',
];
const wordmark = readFileSync(resolve(root, 'assets/icons/ic_logo.svg'), 'utf8')
  .match(/<path\b[^>]*\bd="([^"]+)"/)[1];
const mark = (color = ink) => paths.map(d => `<path fill="${color}" d="${d}"/>`).join('');
const group = (body, x, y, scale = 1) => `<g transform="translate(${x} ${y}) scale(${scale})">${body}</g>`;
const rect = (x, y, w, h, color, r = 0) => `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="${color}"/>`;
const svg = (w, h, body) => `<svg xmlns="${ns}" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">${body}</svg>\n`;
const text = (x, y, value, size = 16, color = ink, weight = 400) =>
  `<text x="${x}" y="${y}" font-family="Inter" font-size="${size}" font-weight="${weight}" fill="${color}">${value}</text>`;
const logo = (x, y, width, color = ink) => group(`<path d="${wordmark}" fill="${color}"/>`, x, y, width / 81);
const write = (path, data) => {
  const dest = resolve(root, path);
  if (!['assets/branding/', 'docs/branding/'].some(prefix => path.startsWith(prefix))) {
    throw new Error(`Output must stay in the standalone branding folders: ${path}`);
  }
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, data);
};
const render = (source, width) => new Resvg(source, {
  fitTo: { mode: 'width', value: width },
  font: {
    loadSystemFonts: false,
    fontFiles: ['Regular', 'Medium', 'SemiBold', 'Bold'].map(weight =>
      resolve(root, `assets/fonts/Inter_18pt-${weight}.ttf`)),
  },
}).render();
const png = (path, source, width) => write(path, render(source, width).asPng());
const asset = (name, source, size) => {
  write(`assets/branding/${name}.svg`, source);
  if (size) png(`assets/branding/${name}.png`, source, size);
};
const vectorPath = (d, color) => `<path android:fillColor="${color}" android:pathData="${d}"/>`;
const vectorMark = (color = ink) => paths.map(d => vectorPath(d, color)).join('\n');
const vector = (size, viewport, body) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/branding/generate.mjs. -->
<vector xmlns:android="${androidNs}"
    android:width="${size}dp" android:height="${size}dp"
    android:viewportWidth="${viewport}" android:viewportHeight="${viewport}">
${body}
</vector>
`;
const res = 'assets/branding/android/res';
write(`${res}/values/brand_colors.xml`, `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/branding/generate.mjs. -->
<resources>
    <color name="stride_lime">${lime}</color>
    <color name="stride_ink">${ink}</color>
    <color name="stride_background">${background}</color>
</resources>
`);

// Full-bleed masters have no baked-in mask or shadow.
const launcher = svg(108, 108, rect(0, 0, 108, 108, lime) + group(mark(), -27, -27, 1.5));
asset('launcher_icon', launcher, 1024);
png('assets/branding/play_store_icon_512.png', launcher, 512);
asset('stride_mark', svg(108, 108, mark()));
asset('launcher_foreground', svg(108, 108, mark()), 432);
asset('launcher_monochrome', svg(108, 108, mark('#FFFFFF')), 432);
const notification = svg(24, 24, group(mark('#FFFFFF'), -6.36, -6.36, 0.34));
asset('notification_icon', notification, 96);

const legacy = svg(108, 108, rect(4, 4, 100, 100, lime, 25) + group(mark(), -22.68, -22.68, 1.42));
const round = svg(108, 108, '<circle cx="54" cy="54" r="50" fill="' + lime + '"/>' + group(mark(), -22.68, -22.68, 1.42));
for (const [density, size, notificationSize] of [
  ['mdpi', 48, 24], ['hdpi', 72, 36], ['xhdpi', 96, 48],
  ['xxhdpi', 144, 72], ['xxxhdpi', 192, 96],
]) {
  png(`${res}/mipmap-${density}/ic_launcher.png`, legacy, size);
  png(`${res}/mipmap-${density}/ic_launcher_round.png`, round, size);
  png(`${res}/drawable-${density}/ic_stat_stride.png`, notification, notificationSize);
}
write(`${res}/drawable/ic_launcher_foreground.xml`, vector(108, 108, vectorMark()));
write(`${res}/drawable/ic_launcher_monochrome.xml`, vector(108, 108, vectorMark('#FFFFFF')));
write(`${res}/drawable-anydpi/ic_stat_stride.xml`, vector(24, 24,
  `<group android:translateX="-6.36" android:translateY="-6.36" android:scaleX="0.34" android:scaleY="0.34">
${vectorMark('#FFFFFF')}
</group>`));
for (const version of [26, 33]) {
  const adaptive = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/branding/generate.mjs. -->
<adaptive-icon xmlns:android="${androidNs}">
    <background android:drawable="@color/stride_lime"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
${version === 33 ? '    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>\n' : ''}</adaptive-icon>
`;
  write(`${res}/mipmap-anydpi-v${version}/ic_launcher.xml`, adaptive);
  write(`${res}/mipmap-anydpi-v${version}/ic_launcher_round.xml`, adaptive);
}

// A 112 dp tile sits inside the 192 dp safe circle on a 288 dp splash canvas.
const splashBranding = svg(200, 80, logo(53, 27, 94));
asset('splash_branding', splashBranding, 800);
const tilePath = 'M120 88 H168 Q200 88 200 120 V168 Q200 200 168 200 H120 Q88 200 88 168 V120 Q88 88 120 88 Z';
// Use the same quadratic corners in SVG and VectorDrawable.
const splashVectorSvg = svg(288, 288, `<path fill="${lime}" d="${tilePath}"/>` + group(mark(), 60, 60, 14 / 9));
asset('splash_icon', splashVectorSvg, 1152);
write(`${res}/drawable/stride_splash_icon.xml`, vector(288, 288,
  vectorPath(tilePath, lime) + '\n' +
  `<group android:translateX="60" android:translateY="60" android:scaleX="1.5555556" android:scaleY="1.5555556">
${vectorMark()}
</group>`));
write(`${res}/drawable/stride_splash_branding.xml`, `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated from the existing assets/icons/ic_logo.svg wordmark. -->
<vector xmlns:android="${androidNs}" android:width="200dp" android:height="80dp"
    android:viewportWidth="200" android:viewportHeight="80">
    <group android:translateX="53" android:translateY="27" android:scaleX="${94 / 81}" android:scaleY="${94 / 81}">
        ${vectorPath(wordmark, ink)}
    </group>
</vector>
`);

// Full-screen preview excludes OS bars. Native Android positions the branding.
const splashPreview = svg(390, 844,
  rect(0, 0, 390, 844, background) + group(splashVectorSvg.replace(/<\/?svg[^>]*>/g, ''), 51, 278) + logo(148, 767, 94));
write('docs/branding/splash_preview.svg', splashPreview);
png('docs/branding/splash_preview.png', splashPreview, 1170);

// Review board: use the actual artwork, including circular and themed masks.
const iconBody = (color = ink) => group(mark(color), -27, -27, 1.5);
const card = (x, y, w, h, color = '#FFFFFF') => rect(x, y, w, h, color, 24);
const miniature = (x, y, size, roundness, bg = lime, fg = ink) =>
  group(rect(0, 0, 108, 108, bg, roundness) + iconBody(fg), x, y, size / 108);
let board = rect(0, 0, 1600, 1120, background);
board += logo(56, 52, 154) + text(238, 86, 'BỘ NHẬN DIỆN ỨNG DỤNG', 18, muted, 500);
board += text(56, 153, 'Mỗi bước, một tiến bộ.', 40, ink, 700);
board += text(56, 187, 'Dấu ↗ của Stride, cô đọng thành biểu tượng cho hành trình tập luyện.', 19, muted);

board += card(56, 228, 524, 460, dark);
board += text(88, 270, '01 / LAUNCHER', 14, lime, 600);
board += miniature(194, 312, 248, 28);
board += text(88, 632, 'Một hướng đi. Từng bước tiến.', 23, '#FFFFFF', 600);
board += text(88, 661, 'Lime × Ink · Hình khối rõ ở mọi kích thước', 16, '#BCC8BF');

board += card(604, 228, 420, 220);
board += text(632, 266, '02 / ADAPTIVE &amp; THEMED', 14, muted, 600);
board += miniature(632, 298, 88, 54) + miniature(737, 298, 88, 26) + miniature(842, 298, 88, 54, '#E0E8D5', '#35472B');
board += text(632, 423, 'Tròn, bo góc và đơn sắc theo hệ thống', 15, muted);

board += card(604, 472, 420, 216);
board += text(632, 510, '03 / NOTIFICATION', 14, muted, 600);
board += rect(628, 535, 372, 100, dark, 20);
board += group(mark('#FFFFFF'), 633, 550, 0.44);
board += text(692, 565, 'stride · Nhắc giờ tập', 14, '#C0CCBD', 500);
board += text(692, 593, '18:00 · Thân trên &amp; core', 18, '#FFFFFF', 600);
board += text(632, 663, 'Silhouette trắng · Nền trong suốt', 15, muted);

board += card(1048, 228, 496, 836, '#E8ECE8');
board += text(1080, 270, '04 / SPLASH SCREEN', 14, muted, 600);
board += rect(1114, 296, 364, 734, ink, 42);
board += rect(1121, 303, 350, 720, background, 36);
board += text(1145, 337, '9:41', 14, ink, 600);
board += group(splashVectorSvg.replace(/<\/?svg[^>]*>/g, ''), 1152, 520);
board += logo(1249, 947, 94);
board += rect(1250, 1004, 92, 4, ink, 2);

board += card(56, 712, 968, 190);
board += text(88, 755, 'BẢNG MÀU TỪ GIAO DIỆN STRIDE', 14, muted, 600);
for (const [i, color, label] of [[0, lime, 'Accent / #D2F36B'], [1, ink, 'Ink / #1C2520'], [2, background, 'Background / #F7F8FA'], [3, '#526C30', 'Green / #526C30']]) {
  const x = 88 + i * 224;
  board += rect(x, 781, 192, 50, color, 12) + text(x, 861, label, 14, muted);
}
board += text(56, 966, 'Đồng bộ từ màn hình chính đến lúc mở app.', 26, ink, 600);
board += text(56, 1005, 'SVG gốc · PNG 1024 / 512 · Android mdpi → xxxhdpi', 18, muted);
board += text(56, 1037, 'Adaptive icon · Monochrome icon · Splash artwork', 18, muted);
board += text(56, 1093, 'stride ↗', 15, ink, 600) + text(1350, 1093, 'BRAND ASSETS / 01', 13, muted, 500);
const preview = svg(1600, 1120, board);
write('docs/branding/preview.svg', preview);
png('docs/branding/preview.png', preview, 1600);
console.log('Exported standalone assets to assets/branding and previews to docs/branding.');
